In [9]:
import pandas as pd

df = pd.read_csv("../../results/init_duration_results.csv")

df.head()

         function_name architecture  memory_size  init_duration_ms
0  lambda-01-arm-512mb        arm64          512             68.45
1  lambda-02-arm-512mb        arm64          512             87.61
2  lambda-03-arm-512mb        arm64          512             85.55
3  lambda-04-arm-512mb        arm64          512             83.72
4  lambda-05-arm-512mb        arm64          512             70.22

In [25]:
df["init_duration_ms"] = pd.to_numeric(
    df["init_duration_ms"],
    errors="coerce"
)

df = df.dropna(subset=["init_duration_ms"])

In [12]:
media = df["init_duration_ms"].mean()
mediana = df["init_duration_ms"].median()
desvio_padrao = df["init_duration_ms"].std()
minimo = df["init_duration_ms"].min()
maximo = df["init_duration_ms"].max()

print(f"Média: {media:.2f} ms")
print(f"Mediana: {mediana:.2f} ms")
print(f"Desvio padrão: {desvio_padrao:.2f} ms")
print(f"Mínimo: {minimo:.2f} ms")
print(f"Máximo: {maximo:.2f} ms")

Média: 82.55 ms
Mediana: 83.66 ms
Desvio padrão: 11.58 ms
Mínimo: 46.16 ms
Máximo: 193.35 ms

In [13]:
df["init_duration_ms"].describe()

count    800.000000
mean      82.549675
std       11.584318
min       46.160000
25%       76.115000
50%       83.660000
75%       87.242500
max      193.350000
Name: init_duration_ms, dtype: float64

In [48]:
df.groupby("architecture")["init_duration_ms"].agg(
    ["count", "mean", "median", "std", "min", "max"]
)

              count     mean  median        std    min     max
architecture
arm64           300  81.5794   83.47  13.030295  46.16  193.35
x86_64          300  83.4646   83.63  10.029432  61.66  155.09

In [27]:
def p95(x):
    return x.quantile(0.95)

def p99(x):
    return x.quantile(0.99)


df.groupby(
    ["architecture", "memory_size"]
)["init_duration_ms"].agg(
    ["count", "mean", "median", "std", "min", "max", p95, p99]
)

                          count     mean  median        std    min     max  \
architecture memory_size
arm64        512            100  80.7603  83.010  11.049496  46.16  128.65
             1024           100  81.5906  83.405  15.725935  47.28  193.35
             2048           100  82.3873  83.760  11.918989  64.84  138.00
             3008           100  80.6722  83.690  12.025372  49.04  145.92
x86_64       512            100  85.2949  84.210  11.625643  65.11  155.09
             1024           100  80.8548  81.630   8.837988  61.66  111.87
             2048           100  84.2441  84.100   8.925111  69.43  123.29
             3008           100  84.5932  84.895  10.425250  67.47  118.91

                               p95       p99
architecture memory_size
arm64        512           90.6680  109.8598
             1024          94.1455  123.7530
             2048          95.5565  122.7144
             3008          92.6035   97.6080
x86_64       512          100.3810  112.8467
             1024          95.8610  101.1384
             2048          99.7125  104.6087
             3008         103.0345  107.8220